/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package HundirLaFlota;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author alumno
 */
public class Tablero extends javax.swing.JPanel{

    int dimensionTablero;
    
    JButton[][] btCasilla;
    
    String[] letra = {"A","B","C","D","E","F","G","H","I","J"};
    String[] numero = {"1","2","3","4","5","6","7","8","9","10"};
    
    JLabel[] lbLetra;
    JLabel[] lbNumero;
    
    /**
     * Creates new form Tablero
     * @param dimensionTablero
     * @param titulo
     */
    public Tablero(int dimensionTablero,String titulo) {
        this.dimensionTablero=dimensionTablero;
        btCasilla = new JButton[dimensionTablero][dimensionTablero];
        setOpaque(false);
        initComponents();
        setBorder(javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createEtchedBorder(), 
                titulo, 
                javax.swing.border.TitledBorder.CENTER, 
                javax.swing.border.TitledBorder.ABOVE_TOP)
                );
        initMoreComponents();   
    }

    public void initMoreComponents(){
        lbLetra = new JLabel[dimensionTablero];
        lbNumero = new JLabel[dimensionTablero];
        
        for (int i = 0; i < dimensionTablero; i++) {
            lbLetra[i] = new JLabel();
            add(lbLetra[i]);
            lbLetra[i].setBounds(10, 35*(i+1), 30, 30);
            lbLetra[i].setText(letra[i]);

            lbNumero[i] = new JLabel();
            add(lbNumero[i]);
            lbNumero[i].setBounds(35*(i+1), 10, 30, 30);
            lbNumero[i].setText(numero[i]);
            
            for (int j = 0; j < dimensionTablero; j++) {
                btCasilla[i][j] = new JButton();
                add(btCasilla[i][j]);
                btCasilla[i][j].setEnabled(true);
                btCasilla[i][j].setBounds(35*(j+1), 35*(i+1), 30, 30);
                btCasilla[i][j].setText("");
            }
        }
    }

    public JButton[][] getBtCasilla() {
        return btCasilla;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));
        setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
    }// </editor-fold>                        
    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
